"""escalations

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 13:07:44.668445
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("risk_tier", sa.SmallInteger(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("callback_number_enc", sa.LargeBinary(), nullable=True),
        sa.Column("partner_ref", sa.String(length=128), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_breached", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_escalations_status_created", "escalations", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_escalations_user_id"), "escalations", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escalations_user_id"), table_name="escalations")
    op.drop_index("ix_escalations_status_created", table_name="escalations")
    op.drop_table("escalations")
    # ### end Alembic commands ###
