#!/usr/bin/env bash
# Create .env with freshly generated LOCAL-ONLY secrets for docker compose.
# Never reuse these values anywhere else.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ] && [ "${1:-}" != "--force" ]; then
  echo ".env already exists (use --force to regenerate; this makes existing local data unreadable)."
  exit 0
fi

python3 - > .env <<'PY'
import base64, os, secrets
print("# Local docker compose secrets — generated by scripts/dev-env.sh. Do not commit.")
print(f"KOYALA_MASTER_KEY={base64.b64encode(os.urandom(32)).decode()}")
print(f"KOYALA_JWT_SECRET={secrets.token_urlsafe(48)}")
print(f"KOYALA_PARTNER_TOKEN={secrets.token_urlsafe(24)}")
print("KOYALA_LLM_PROVIDER=stub")
print("KOYALA_RISK_JUDGE=off")
print("# To use Claude: set KOYALA_LLM_PROVIDER=anthropic and ANTHROPIC_API_KEY=...")
print("ANTHROPIC_API_KEY=")
PY
chmod 600 .env
echo "Wrote .env. Next: docker compose up --build"
